import {type DeployEnv} from '@evir/common';
import {generateNewJwtKeys, type RawJwtKeys} from 'auth-vir';
import {defineSecrets, type SecretValues} from 'updating-secrets';

export function defineBackendSecrets(deployEnv: DeployEnv) {
    return defineSecrets({
        jwtKeys: {
            description: 'The keys required for JWT auth to function.',
            whereToFind:
                'These are randomly generated and stored either locally in a config file (in dev) or in AWS Secrets Manager.',
            adapterConfig: {
                aws: {
                    keyIn: [
                        deployEnv,
                        'BackendSecrets',
                    ].join('/'),
                },
            },
            shape: {
                encryptionKey: '',
                signingKey: '',
            } satisfies RawJwtKeys,
        },
        database: {
            description: 'All connection parameters required for connecting to the database.',
            whereToFind:
                'These are automatically generated by AWS RDS and stored in AWS Secrets Manager. This is not used in dev.',
            adapterConfig: {
                aws: {
                    rootOf: [
                        deployEnv,
                        'DatabaseCredentials',
                    ].join('/'),
                },
            },
            shape: {
                password: '',
                dbname: '',
                engine: '',
                port: -1,
                host: '',
                username: '',
            },
        },
    });
}

export type BackendSecretDefinitions = ReturnType<typeof defineBackendSecrets>;

export async function generateDevSecrets(): Promise<SecretValues<BackendSecretDefinitions>> {
    return {
        jwtKeys: await generateNewJwtKeys(),
        /** `database` secrets are not applicable in dev. */
        database: undefined as any,
    };
}
